### ISSUE TITLE
TypeError: new_traced_event() missing 2 required positional arguments: 'trace_id' and 'parent_id'

### ISSUE THREAD

**Issue by afausti** [honeycombio/beeline-python#20]
I've just tried `honeycomb-beeline` to instrument my Flask app following the instructions at https://docs.honeycomb.io/getting-data-in/beelines/beeline-python/ but I am getting this error:

```
127.0.0.1 - - [07/Sep/2018 09:30:38] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/afausti/Projects/squash-demo/squash-deployment/squash-restful-api/env/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/afausti/Projects/squash-demo/squash-deployment/squash-restful-api/env/lib/python3.6/site-packages/beeline/middleware/flask/__init__.py", line 40, in __call__
    }, trace_name=trace_name, top_level=True)
  File "/Users/afausti/Projects/squash-demo/squash-deployment/squash-restful-api/env/lib/python3.6/site-packages/beeline/__init__.py", line 183, in _new_event
    ev = g_tracer.new_traced_event(trace_name)
TypeError: new_traced_event() missing 2 required positional arguments: 'trace_id' and 'parent_id'
```
Here is how I am  invoking the beeline in my app:

```
import os
import beeline
from beeline.middleware.flask import HoneyMiddleware

from app import create_app, db

profile = os.environ.get('SQUASH_API_PROFILE', 'app.config.Development')
honey_api_key = os.environ.get('HONEY_API_KEY')

app = create_app(profile)

beeline.init(writekey=honey_api_key, dataset="squash-rest-api", service_name="squash")

HoneyMiddleware(app, db_events=True)
```

I see the same with

```
HoneyMiddleware(app, db_events= False)
```

The versions I am running:
```
Flask             1.0.2
Flask-RESTful     0.3.6
Flask-SQLAlchemy  2.3.2
honeycomb-beeline 1.2.0
libhoney          1.5.0
```

**Comment by afausti** [comment]
Thank you for the quick fix! I am already seeing data flowing to my new dataset.
