### ISSUE TITLE
[flask] Beeline trying to get dict fields which do not exist

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-python#22]
from pollinators:

```
spawned uWSGI http 1 (pid: 78)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/beeline/middleware/flask/__init__.py", line 37, in __call__
    "request.user_agent": environ['HTTP_USER_AGENT'],
KeyError: 'HTTP_USER_AGENT'
```

**Comment by nathanleclaire** [comment]
ping @asdvalenzuela probably at a minimum we should be using `.get` everywhere
